#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

# Activate VirtualEnv in order to use the correct libraries
echo 'linking images from $OPENSHIFT_DATA_DIR/images to $OPENSHIFT_REPO_DIR/wsgi/static/images'
if [ ! -d $OPENSHIFT_DATA_DIR/images ]; then
mkdir $OPENSHIFT_DATA_DIR/images
fi
 
ln -sf $OPENSHIFT_DATA_DIR/images $OPENSHIFT_REPO_DIR/wsgi/static/images
